services:
  - docker

script:
#  - docker login docker.pkg.github.com -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker build -t docker.pkg.github.com/ittocean/docker-registry-browser/docker-registry-browser:$TRAVIS_BUILD_NUMBER .
#  - docker push docker.pkg.github.com/ittocean/docker-registry-browser/docker-registry-browser:$TRAVIS_BUILD_NUMBER
